### ISSUE TITLE
restarting redis hangs chef-solo

### ISSUE THREAD

**Issue by suan** [ctrabold/chef-redis#4]
Not sure if anyone else is seeing this...

I'm using just the defaults (ie package installation) on Vagrant with chef-solo. The very first time redis is being installed, chef-solo hangs at the part where the `redis.conf` template is reloaded, and the redis service is restarted. If I kill the run and start it all over again, everything's fine.

**Comment by alhafoudh** [comment]
+1

**Comment by jackkordas** [comment]
The default config installed does not daemonize redis.  Thus, the restart hangs as its running in the foreground.

in attributes/default.rb we have:  default['redis']['daemonize']    = "no"

You can override redis.daemonize to yes to resolve the hang.

**Comment by suan** [comment]
@jackkordas Any reason why you guys dont want it daemonized?

**Comment by jackkordas** [comment]
I'm not sure why no is the default here.  I'm not the originator of the cookbook, just trying to make use of it.

**Comment by tigris** [comment]
Just discovered this also. I changed it to "yes" in my node json file, but if you reboot before you run chef solo again you are screwed. In my case, chef solo runs after boot. Had to boot in rescue mode to change it manually.
